Add translator
yiisoft/app pull request #257
Opened 2022-11-04 00:09 UTC by xepozz

| Q             | A
| ------------- | ---
| Is bugfix?    | ✔️
| New feature?  | ✔️
| Breaks BC?    | ❌

2022-11-05 15:39 UTC, vjik requested changes

2022-11-05 15:39 UTC, vjik commented on config/common/translator.php
> +    'translation.app' => static function (Aliases $aliases, MessageFormatterInterface $messageFormatter) use ($params) {
`MessageFormatterInterface` don't should defined in container. Use concrete implementation specfic to category.

2022-11-06 05:50 UTC, vjik approved these changes

2022-11-06 07:20 UTC, samdark approved these changes

2022-11-06 07:20 UTC, merged